name: Build and Publish
on:
  push:
    branches:
      - master
      - 'release-*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

  workflow_dispatch:

jobs:
  build-publish-docker-helm:
    name: Build & Publish Docker Image & Helm Chart
    runs-on: ubuntu-latest
    env:
      HELM_CHART_PATH: package/helm/
    steps:
      - uses: actions/checkout@v2

      #crear el tag de manera automatica con un contador
      - name: Calculate new tag version
        id: new_tag
        run: |
            git fetch --tags
            lastTag=$(git describe --tags `git rev-list --tags --max-count=1`)
            echo "Last tag: $lastTag"
            major=$(echo $lastTag | cut -d. -f1)
            minor=$(echo $lastTag | cut -d. -f2)
            patch=$(echo $lastTag | cut -d. -f3)
            patch="v$major.$minor.$((patch + 1))"
            echo "New tag: $patch"
            echo ::set-output name=new_tag::$patch

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          push: true
          tags: juanjortega/oclapi2-fhir:${{ steps.new_tag.outputs.new_tag }},juanjortega/oclapi2-fhir:latest
          
      - name: Update Version and Image Tag
        run: |
          yq --inplace '.image.tag = "${{ steps.new_tag.outputs.new_tag }}"' $HELM_CHART_PATH/values.yaml
          yq --inplace '.version = "${{ steps.new_tag.outputs.new_tag }}"' $HELM_CHART_PATH/Chart.yaml
      - name: Helm Lint
        run: helm lint $HELM_CHART_PATH

      - name: Helm Package
        run: helm package $HELM_CHART_PATH

      - name: Checkout Charts Repository
        uses: actions/checkout@v2
        with:
          repository: juanjortega/helm-charts
          ref: gh-pages
          path: helm-charts
          persist-credentials: false

      - name: Copy Helm Archive
        run: cp oclapi2-fhir-${{ env.ARTIFACT_VERSION }}.tgz helm-charts/oclapi2-fhir/

      - name: Helm Index
        working-directory: helm-charts/
        run: helm repo index --merge index.yaml --url https://juanjortega.github.io/helm-charts/  .

      - name: Commit and Push Chart Repository
        working-directory: helm-charts/
        run: |
          git config user.name ${{ secrets.BAHMNI_USERNAME}}
          git config user.email ${{ secrets.BAHMNI_EMAIL}}
          git add .
          git commit -m "Release of bahmni-web-${{ env.ARTIFACT_VERSION }}"
          git push 'https://${{ secrets.BAHMNI_USERNAME}}:${{ secrets.BAHMNI_PAT}}@github.com/bahmni/helm-charts.git' gh-pages
